agrofarm/data/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class Login(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20))
    email = db.Column(db.String(20))

    def __init__(self, name, email):
        self.name = name
        self.email = email

    def __repr__(self):
        return '<Id: %r, User: %r, Email: %r>' % (self.id, self.name, self.email)


class Users(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(30), nullable=False, unique=True)
    password = db.Column(db.String(32), nullable=False)

    def __init__(self, name, email, password):
        self.name = name
        self.email = email
        self.password = password

    def __repr__(self):
        return '<Id: %r, Name: %r, Email: %r, Password: %r>' % (self.id, self.name, self.email, self.password)


class Questions(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(500), nullable=False)
    details = db.Column(db.String, nullable=False)
    asked = db.Column(
        db.DateTime, server_default=db.func.now(), nullable=False)
    u_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    upvotes = db.Column(db.Integer, default=0)
    downvotes = db.Column(db.Integer, default=0)

    def __init__(self, title, details, u_id, upvotes=None, downvotes=None):
        self.title = title
        self.details = details
        self.u_id = u_id
        self.upvotes = upvotes
        self.downvotes = downvotes

    def __repr__(self):
        return '<Id: %r, Title: %r, Details: %r, Asked: %r, User_ID: %r, Upvotes: %r, Downvotes: %r' % (self.id, self.title, self.details, self.asked, self.u_id, self.upvotes, self.downvotes)


class Answers(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    ans = db.Column(db.String, nullable=False)
    answered = db.Column(
        db.DateTime, server_default=db.func.now(), nullable=False)
    q_id = db.Column(db.Integer, db.ForeignKey("questions.id"), nullable=False)
    u_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    upvotes = db.Column(db.Integer, default=0)
    downvotes = db.Column(db.Integer, default=0)
    accepted = db.Column(db.Enum('YES', 'NO', name='ACCEPT_ANS'), default="NO")

    def __init__(self, ans, q_id, u_id, upvotes=None, downvotes=None, accepted=None):
        self.ans = ans
        self.q_id = q_id
        self.u_id = u_id
        self.upvotes = upvotes
        self.downvotes = downvotes
        self.accepted = accepted

    def __repr__(self):
        return '<Id: %r, Answer: %r, Answered: %r, Question_Id: %r, User_ID: %r, Upvotes: %r, Downvotes: %r, Accepted: %r' % (self.id, self.ans, self.answered, self.q_id, self.u_id, self.upvotes, self.downvotes, self.accepted)


class q_votes(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    u_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    q_id = db.Column(db.Integer, db.ForeignKey("questions.id"), nullable=False)
    vote = db.Column(db.Enum('UP', 'DOWN', name='VOTE_TYPE'), default="NO")
    __table_args__ = (db.UniqueConstraint('u_id', 'q_id'),)

    def __init__(self, u_id, q_id, vote):
        self.u_id = u_id
        self.q_id = q_id
        self.vote = vote

    def __repr__(self):
        return '<Id: %r, User_ID: %r, Question_Id: %r, Vote: %r' % (self.id, self.u_id, self.q_id, self.vote)


class a_votes(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    u_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    a_id = db.Column(db.Integer, db.ForeignKey("answers.id"), nullable=False)
    vote = db.Column(db.Enum('UP', 'DOWN', name='VOTE_TYPE'), default="NO")
    __table_args__ = (db.UniqueConstraint('u_id', 'a_id'),)

    def __init__(self, u_id, a_id, vote):
        self.u_id = u_id
        self.a_id = a_id
        self.vote = vote

    def __repr__(self):
        return '<Id: %r, User_ID: %r, Answer_Id: %r, Vote: %r' % (self.id, self.u_id, self.a_id, self.vote)

agrofarm/__init__.py
from flask import Flask, render_template, request

from agrofarm.admin.controllers import admin
#from agrofarm.cache import cache
from agrofarm.config import configure_app
from agrofarm.data.models import db
#from flask import abort, Flask, g, render_template, request
#from flask_babel import Babel
#from flask_security import current_user
#from bookshelf.utils import get_instance_folder_path
from agrofarm.main.controllers import main

app = Flask(__name__,
            # instance_path=get_instance_folder_path(),
            instance_relative_config=True,
            template_folder='templates')

#babel = Babel(app)
configure_app(app)
# cache.init_app(app)
db.init_app(app)
# app.jinja_env.add_extension('jinja2.ext.loopcontrols')
# @app.url_defaults
# def set_language_code(endpoint, values):
#    if 'lang_code' in values or not g.get('lang_code', None):
#        return
#    if app.url_map.is_endpoint_expecting(endpoint, 'lang_code'):
#        values['lang_code'] = g.lang_code

# @app.url_value_preprocessor
# def get_lang_code(endpoint, values):
#    if values is not None:
#        g.lang_code = values.pop('lang_code', None)

# @app.before_request
# def ensure_lang_support():
#    lang_code = g.get('lang_code', None)
#    if lang_code and lang_code not in app.config['SUPPORTED_LANGUAGES'].keys():
#        return abort(404)

# @babel.localeselector
# def get_locale():
#    return g.get('lang_code', app.config['BABEL_DEFAULT_LOCALE'])

# @babel.timezoneselector
# def get_timezone():
#    user = g.get('user', None)
#    if user is not None:
#        return user.timezone


@app.errorhandler(400)
def bad_requert_error(error):
    app.logger.error('Bad Request: %s', (request.path, error))
    return render_template('400.html'), 400


@app.errorhandler(404)
def page_not_found(error):
    app.logger.error('Page not found: %s', (request.path, error))
    return render_template('404.html'), 404


@app.errorhandler(405)
def method_not_allowed(error):
    app.logger.error('Method Not Allowed: %s', (request.path, error))
    return render_template('405.html'), 405


@app.errorhandler(500)
def internal_server_error(error):
    app.logger.error('Server Error: %s', (error))
    return render_template('500.html'), 500


@app.errorhandler(Exception)
def unhandled_exception(error):
    app.logger.error('Unhandled Exception: %s', (error))
    return render_template('500.html'), 500

# @app.context_processor
# def inject_data():
#    return dict(user=current_user, \
#        lang_code=g.get('lang_code', None))

# @app.route('/')
# @app.route('/<lang_code>/')
# @cache.cached(300)
# def home():
#    return render_template('home.html')


app.register_blueprint(main, url_prefix='/')
#app.register_blueprint(main, url_prefix='/<lang_code>/main')
app.register_blueprint(admin, url_prefix='/admin')
#app.register_blueprint(admin, url_prefix='/<lang_code>/admin')

agrofarm/admin/controllers.py
from flask import Blueprint

admin = Blueprint("admin", __name__)


@admin.route("/")
def index():
    return "Admin"

agrofarm/main/controllers.py
from __future__ import unicode_literals

import hashlib
import json

from elasticsearch import Elasticsearch
from flask import (
    Blueprint,
    current_app,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from sqlalchemy import exc, text

from agrofarm.data.models import Answers, Login, Questions, Users, a_votes, db, q_votes

es = Elasticsearch()

# specifies the template folder for the main blueprint
main = Blueprint("main", __name__, template_folder="templates", static_folder="/static")


@main.route("/")
def index():
    result = (
        db.session.query(Questions, db.func.count(Answers.q_id))
        .group_by(Questions.id)
        .order_by(Questions.asked.desc())
        .outerjoin(Answers)
        .all()
    )
    return render_template("home.html", result=result)


@main.route("account")
def account():
    if "u_name" in session:
        return redirect(url_for("main.profile"))
    return render_template("login_signup.html")


@main.route("about")
def about():
    return render_template("about.html")


@main.route("signIn", methods=["POST"])
def signIn():
    if request.method != "POST":
        return render_template("405.html")
    if "u_name" in session:
        return redirect(url_for("main.profile"))

    request_data = request.get_json(force=True)

    if (
        not request_data["email"]
        or not request_data["password"]
        or request_data["email"].isspace()
        or request_data["password"].isspace()
    ):
        response = {"status": 1, "status_msg": "Data Not Found"}
        return jsonify(response), 200

    email = request_data["email"]
    password = request_data["password"]
    hash_object = hashlib.md5(password.encode())
    hashed_password = hash_object.hexdigest()
    result = Users.query.filter_by(email=email).first()
    if result is None:
        response = {"status": 1, "status_msg": "User Not Found"}
        return jsonify(response), 200
    else:
        if hashed_password == result.password:
            session["u_id"] = result.id
            session["u_name"] = result.name
            session["u_email"] = result.email
            response = {"status": 0, "status_msg": "Success!"}
            return jsonify(response), 200
        else:
            response = {"status": 1, "status_msg": "Mismatch!"}
            return jsonify(response), 200


@main.route("signOut")
def signOut():
    if "u_name" in session:
        session.pop("u_name", None)
        session.pop("u_id", None)
        return redirect(url_for("main.index"))

    return redirect(url_for("main.account"))


@main.route("signUp", methods=["POST"])
def add_new_user():
    if request.method != "POST":
        return render_template("405.html")
    if "u_name" in session:
        return redirect(url_for("main.profile"))

    request_data = request.get_json(force=True)

    if (
        not request_data["name"]
        or not request_data["email"]
        or not request_data["password"]
        or request_data["name"].isspace()
        or request_data["email"].isspace()
        or request_data["password"].isspace()
    ):
        response = {"status": 1, "status_msg": "Data Not Found"}
        return jsonify(response), 200

    name = request_data["name"]
    email = request_data["email"]
    password = request_data["password"]
    hash_object = hashlib.md5(password.encode())
    hashed_password = hash_object.hexdigest()
    current_app.logger.info(
        "Adding a new User {0}: {1}: {2}.".format(name, email, hashed_password)
    )
    add_user = Users(name, email, hashed_password)

    try:
        db.session.add(add_user)
        db.session.commit()
        result = Users.query.order_by(Users.id.desc()).first()
        es.index(
            index="agrofarm",
            doc_type="users",
            id=result.id,
            body={"id": result.id, "name": result.name, "email": result.email},
        )
        session["u_id"] = result.id
        session["u_name"] = result.name
        session["u_email"] = result.email
        response = {"status": 0, "status_msg": "Success!"}
        return jsonify(response), 201
    except exc.SQLAlchemyError as e:
        flash("Cannot Add User.")
        current_app.logger.error(e)
        response = {"status": 1, "status_msg": "User Not Added!"}
        return jsonify(response), 500


@main.route("profile")
def profile():
    if "u_name" in session:
        u_id = session["u_id"]
        question = Questions.query.filter_by(u_id=u_id).all()
        result = (
            db.session.query(Answers, Questions.title)
            .filter_by(u_id=u_id)
            .join(Questions)
        )
        return render_template("profile.html", question=question, answer=result)
    else:
        return redirect(url_for("main.account"))


@main.route("questions")
def ask_question():
    return render_template("questions.html")


@main.route("submit_question", methods=["POST"])
def submit_question():
    if request.method != "POST":
        return render_template("405.html")
    if "u_name" not in session:
        return redirect(url_for("main.account"))

    request_data = request.get_json(force=True)

    if (
        not request_data["title"]
        or not request_data["text"]
        or request_data["title"].isspace()
        or request_data["text"].isspace()
    ):
        response = {"status": 1, "status_msg": "Data Not Found"}
        return jsonify(response), 200

    title = request_data["title"]
    text = request_data["text"]
    u_id = session["u_id"]
    current_app.logger.info(
        "Adding a new Question: U_Id: {0}, title: {1}, text: {2}".format(
            u_id, title, text
        )
    )
    add_question = Questions(title, text, u_id)

    try:
        db.session.add(add_question)
        db.session.commit()
        esresult = Questions.query.order_by(Questions.id.desc()).first()
        es.index(
            index="agrofarm",
            doc_type="questions",
            id=esresult.id,
            body={
                "id": esresult.id,
                "title": esresult.title,
                "details": esresult.details,
                "asked": esresult.asked,
                "u_id": esresult.u_id,
                "upvotes": esresult.upvotes,
                "downvotes": esresult.downvotes,
            },
        )
        response = {"status": 0, "status_msg": "Success!"}
        return jsonify(response), 201
    except exc.SQLAlchemyError as e:
        flash("Cannot Add Question.")
        current_app.logger.error(e)
        response = {"status": 1, "status_msg": "Question Not Added!"}
        return jsonify(response), 500


@main.route("view_question/<int:q_id>")
def view_question(q_id):
    question = (
        db.session.query(Questions, Users.name).filter_by(id=q_id).join(Users).first()
    )
    answer_accepted = (
        db.session.query(Answers, Users.name)
        .filter_by(q_id=q_id, accepted="YES")
        .join(Users)
        .first()
    )
    all_answers = (
        db.session.query(Answers, Users.name)
        .filter_by(q_id=q_id, accepted="NO")
        .order_by(Answers.upvotes.desc(), Answers.answered.desc())
        .join(Users)
        .all()
    )

    if not all_answers and not answer_accepted:
        ques_suggestions = es.search(
            index="agrofarm", doc_type="questions", q=question[0].title, size=5
        )
        ans_suggestions = es.search(
            index="agrofarm", doc_type="answers", q=question[0].title, size=5
        )
    else:
        ques_suggestions = None
        ans_suggestions = None

    return render_template(
        "view_question.html",
        question=question,
        answer_accepted=answer_accepted,
        all_answers=all_answers,
        ques_suggestions=ques_suggestions,
        ans_suggestions=ans_suggestions,
    )


@main.route("submit_answer/<int:q_id>", methods=["POST"])
def submit_answer(q_id):
    if request.method != "POST":
        return render_template("405.html")
    if "u_name" not in session:
        response = {"status": 1, "status_msg": "You need to login first to answer!"}
        return jsonify(response), 200

    request_data = request.get_json(force=True)
    if not request_data["ans"] or request_data["ans"].isspace():
        response = {"status": 1, "status_msg": "Data Not Found"}
        return jsonify(response), 200

    ans = request_data["ans"]
    u_id = session["u_id"]
    user_answered = Answers.query.filter_by(u_id=u_id, q_id=q_id).first()
    if user_answered is not None:
        response = {
            "status": 1,
            "status_msg": "You have already answered this question!",
        }
        return jsonify(response), 200
    current_app.logger.info(
        "Adding a new Answer to question ({0}: {1}: {2}).".format(u_id, q_id, ans)
    )
    add_answer = Answers(ans, q_id, u_id)

    try:
        db.session.add(add_answer)
        db.session.commit()
        esresult = Answers.query.order_by(Answers.id.desc()).first()
        es.index(
            index="agrofarm",
            doc_type="answers",
            id=esresult.id,
            body={
                "id": esresult.id,
                "ans": esresult.ans,
                "q_id": esresult.q_id,
                "answered": esresult.answered,
                "u_id": esresult.u_id,
                "upvotes": esresult.upvotes,
                "downvotes": esresult.downvotes,
                "accepted": esresult.accepted,
            },
        )
        response = {"status": 0, "status_msg": "Success!"}
        return jsonify(response), 201
    except exc.SQLAlchemyError as e:
        flash("Cannot Add Question.")
        current_app.logger.error(e)
        response = {"status": 1, "status_msg": "Question Not Added!"}
        return jsonify(response), 500


@main.route("help")
def help():
    return render_template("help.html")


@main.route("ans_guide")
def ans_guide():
    return render_template("ans_guide.html")

agrofarm/templates/405.html
{% include '/header.html' %}
<h2>Oops! That's Not Allowed!</h2>
<p>The request method is not supported for the requested resource.</p>
{% include '/footer.html' %}

agrofarm/templates/footer.html
      <div class = "footer">
        <div class="copyright">
          <div class="container">
            <div class="col-md-6">
              <p>© 2017 - All Rights with <span class="glyphicon glyphicon-leaf">agroFarm</span></p>
            </div>
            <div class="col-md-6">
              <ul class="bottom_ul">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('main.ask_question') }}">Questions</a></li>
                <li><a href="{{ url_for('main.about') }}">About</a></li>
                <li><a href="{{ url_for('main.help') }}">Help Center</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
  <script>
  $(".nav a").on("click", function(){
    $(".nav").find(".active").removeClass("active");
    $(this).parent().addClass("active");
  });
  </script>
</html>

agrofarm/templates/view_question.html
{% include '/header.html' %}
<script>
  var flag = 0;
  {% if answer_accepted: %}
  {% if answer_accepted[0].u_id == session['u_id']: %}
  flag = 1;
  {% endif %}
  {% endif %}
  {% for data in all_answers %}
  {% if data[0].u_id == session['u_id']: %}
  flag = 1;
  {% endif %}
  {% endfor %}
  if(flag==1){
    $(document).ready(function() {
      $("#answer_me").hide();
    });
  }
  else{
    $(document).ready(function() {
      $("#answer_me").show();
    });
  }
</script>
<script>
{% if 'u_id' not in session or question[0].u_id != session['u_id'] or answer_accepted: %}
  $(document).ready(function() {
    $("[id=accept]").hide();
  });
{% endif %}
</script>
<div class = "container-fluid">
  <div class="row">
    <div class="col-sm-12">
      {% block question %}
      <h4>{{question[0].title}} </h4>
      <hr />
          <table>
            <tbody>
              <tr>
                <td class="vote-cell">
                  <a class="vote" title="This question is useful and clear" id="vote_up" data-vote-up="UP" data-type-up="QUESTION" data-id-up="{{question[0].id}}"><span class="glyphicon glyphicon-menu-up"></span></a>
                  <span class="view-count">{{question[0].upvotes - question[0].downvotes}}</span>
                  <a class="vote" title="This question is unclear or not useful" id="vote_down" data-vote-down="DOWN" data-type-down="QUESTION" data-id-down="{{question[0].id}}"><span class="glyphicon glyphicon-menu-down"></span></a>
                </td>
                <td class="data-cell">
                  {% for line in question[0].details.splitlines() %}
                  {{line}}<br />
                  {% endfor %}
                  <table>
                    <tbody>
                      <tr>
                        <td class="asked-panel">
                          <span class="asked-label">Asked:</span>
                          <div><script>document.write(moment("{{question[0].asked}}").format('lll'))</script></div>
                          <div>{{question[1]}}</div>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
            </tbody>
          </table>
          {% endblock %}
          <hr />
          <div class="row">
          {% if ques_suggestions and ques_suggestions['hits']['total'] != 0: %}
            <div class="col-sm-6">
              <h4>Suggested Questions:</h4>
              <table class="table table-responsive">
                <tbody>
                  {% for data in ques_suggestions['hits']['hits']: %}
                  {% if not loop.first: %}
                  <tr>
                    <td class="count-cell">
                      <div class="mini-count">{{data['_source']['upvotes'] - data['_source']['downvotes']}}<br />Votes</div>
                    </td>
                    <td>
                      <a href="{{url_for('main.view_question', q_id=data['_source']['id'])}}">{{data['_source']['title']}}</a>
                    </td>
                  </tr>
                  {% endif %}
                  {% endfor %}
                </tbody>
              </table>
            </div>
            {% endif %}
            {% if ans_suggestions and ans_suggestions['hits']['total'] != 0: %}
            <div class="col-sm-6">
              <h4>Suggested Answers:</h4>
              <table class="table table-responsive">
                <tbody>
                  {% for data in ans_suggestions['hits']['hits']: %}
                  <tr>
                    <td class="count-cell">
                      <div class="mini-count">{{data['_source']['upvotes'] - data['_source']['downvotes']}}<br />Votes</div>
                    </td>
                    <td>
                      <a href="{{url_for('main.view_question', q_id=data['_source']['q_id'])}}">{{data['_source']['ans']|truncate(200, True)}}</a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            {% endif %}
          </div>
          <legend>Answers: </legend>
          <div id="answer_me" name="answer_me">
            <div class="col-sm-12">
      	       <h3><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Answer</h3>
               <form role="form" class="answer-form" name="answer_form" id="answer_form" data-toggle="validator">
                 <div class="form-group">
                   <label class="control-label" for="answer-form-text">Answer</label>
                   <textarea form="answer_form" rows="5" name="answer-form-text" placeholder="Answer" class="form-control" id="answer-form-text" required></textarea>
                   <div class="help-block with-errors"></div>
                 </div>
                 <button type="submit" name = "answer_button" id = "answer_button" class="btn btn-primary custom_btn btn-lg btn-block">Answer</button>
               </form>
               <hr />
             </div>
           </div>

          {% block ACCEPTED_ANSWER %}
          {% if answer_accepted: %}
              <table>
                <tbody>
                  <tr>
                    <td class="vote-cell">
                      <a class="vote" title="This answer is useful and clear" id="vote_up" data-vote-up="UP" data-type-up="ANSWER" data-id-up="{{answer_accepted[0].id}}"><span class="glyphicon glyphicon-menu-up"></span></a>
                      <span class="view-count">{{answer_accepted[0].upvotes - answer_accepted[0].downvotes}}</span>
                      <a class="vote" title="This question is unclear or not useful" id="vote_down" data-vote-down="DOWN" data-type-down="ANSWER" data-id-down="{{answer_accepted[0].id}}"><span class="glyphicon glyphicon-menu-down"></span></a>
                      <a class="vote accepted" title="This answer is the most useful one" id="accepted" data-id = "{{ answer_accepted[0].id }}"><span class="glyphicon glyphicon-ok"></span></a>
                    </td>
                    <td class="data-cell">
                      {% for line in answer_accepted[0].ans.splitlines() %}
                      {{line}}<br />
                      {% endfor %}
                      <table>
                        <tbody>
                          <tr>
                            <td class="asked-panel">
                              <span class="asked-label">Answered:</span>
                              <div><script>document.write(moment("{{answer_accepted[0].answered}}").format('lll'))</script></div>
                              <div>{{answer_accepted[1]}}</div>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                </tbody>
              </table>
              <hr />
              {% endif%}
              {% endblock %}
              {% block ALL_ANSWERS %}
              {% for data in all_answers %}
              <table>
                <tbody>
                  <tr>
                    <td class="vote-cell">
                      <a class="vote" title="This answer is useful and clear" id="vote_up" data-vote-up="UP" data-type-up="ANSWER" data-id-up="{{data[0].id}}"><span class="glyphicon glyphicon-menu-up"></span></a>
                      <span class="view-count">{{data[0].upvotes - data[0].downvotes}}</span>
                      <a class="vote" title="This question is unclear or not useful" id="vote_down" data-vote-down="DOWN" data-type-down="ANSWER" data-id-down="{{data[0].id}}"><span class="glyphicon glyphicon-menu-down"></span></a>
                      <a class="vote accept" title="This answer is the most useful one" id="accept" data-id = "{{ data[0].id }}"><span class="glyphicon glyphicon-ok"></span></a>
                    </td>
                    <td class="data-cell">
                      {#{data[0].ans}#}
                      {% for line in data[0].ans.splitlines() %}
                      {{line}}<br />
                      {% endfor %}
                      <table>
                        <tbody>
                          <tr>
                            <td class="asked-panel">
                              <span class="asked-label">Answered:</span>
                              <div><script>document.write(moment("{{data[0].answered}}").format('lll'))</script></div>
                              <div>{{data[1]}}</div>
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </td>
                  </tr>
                </tbody>
              </table>
              <hr />
              {% endfor %}
              {% endblock %}
        </div>
<script>
$(document).ready(function(){
  $('[id=vote_up]').click(function(e){
    $.ajax({
      data: JSON.stringify({"vote": $(this).attr("data-vote-up"), "id": $(this).attr("data-id-up"), "type": $(this).attr("data-type-up")}),
      type: 'POST',
      url: '{{ url_for("main.vote") }}',
      dataType: 'json',
      contentType: 'applicaton/json',
      success: function(result){
        if(result['status']==0){
          window.location.replace("{{url_for('main.view_question', q_id=question[0].id)}}");
        }
        else{
          alert(result['status_msg']);
        }
      }
    });
    e.preventDefault();
  });
});
</script>
<script>
$(document).ready(function(){
  $('[id=vote_down]').click(function(e){
    $.ajax({
      data: JSON.stringify({"vote": $(this).attr("data-vote-down"), "id": $(this).attr("data-id-down"), "type": $(this).attr("data-type-down")}),
      type: 'POST',
      url: '{{ url_for("main.vote") }}',
      dataType: 'json',
      contentType: 'applicaton/json',
      success: function(result){
        if(result['status']==0){
          window.location.replace("{{url_for('main.view_question', q_id=question[0].id)}}");
        }
        else{
          alert(result['status_msg']);
        }
      }
    });
    e.preventDefault();
  });
});
</script>
<script>
$(document).ready(function(){
  $('#answer_form').submit(function(e){
    if(!$('#answer-form-text').val())
    {
      alert("Data Required!")
      return false;
    }
    $.ajax({
      data: JSON.stringify({"ans": $('#answer-form-text').val()}),
      type: 'POST',
      url: '{{ url_for("main.submit_answer", q_id=question[0].id) }}',
      dataType: 'json',
      contentType: 'applicaton/json',
      success: function(result){
        if(result['status']==0){
          window.location.replace("{{ url_for('main.view_question', q_id=question[0].id, _external=True) }}");
        }
        else{
          alert(result['status_msg']);
        }
      }
    });
    e.preventDefault();
  });
});
</script>
<script>
$(document).ready(function(){
  $('[id=accept]').click(function(e){
    $.ajax({
      data: JSON.stringify({"a_id": $(this).attr("data-id"), "q_id": "{{ question[0].id }}"}),
      type: 'POST',
      url: '{{ url_for("main.accept") }}',
      dataType: 'json',
      contentType: 'applicaton/json',
      success: function(result){
        if(result['status']==0){
          window.location.replace("{{url_for('main.view_question', q_id=question[0].id)}}");
        }
        else{
          alert(result['status_msg']);
        }
      }
    });
    e.preventDefault();
  });
});
</script>
<script>
$(document).ready(function(){
  $('[id=accepted]').click(function(e){
    $.ajax({
      data: JSON.stringify({"a_id": $(this).attr("data-id"), "q_id": "{{ question[0].id }}"}),
      type: 'POST',
      url: '{{ url_for("main.accept") }}',
      dataType: 'json',
      contentType: 'applicaton/json',
      success: function(result){
        if(result['status']==0){
          window.location.replace("{{url_for('main.view_question', q_id=question[0].id)}}");
        }
        else{
          alert(result['status_msg']);
        }
      }
    });
    e.preventDefault();
  });
});
</script>
{%include '/footer.html'%}